### ISSUE TITLE
Feature: Reduce frequency of disconnected validator messages on-screen

### ISSUE THREAD

**Issue by michaelbnewman** [ava-labs/gecko#110]
Especially when the network goes down, the on-screen messages show sub-one second repeated messages about disconnected validators which is a fire hose of info. Note the first and last lines are the same info character for character.

`WARN [04-27|16:57:57] /networking/voting_handlers.go#363: Attempted to send a PullQuery message to a disconnected validator: EkKeGSLUbHrrtuayBtbwgWDRUiAziC3ao

WARN [04-27|16:57:57] /networking/voting_handlers.go#363: Attempted to send a PullQuery message to a disconnected validator: NX4zVkuiRJZYe6Nzzav7GXN3TakUet3Co

WARN [04-27|16:57:57] /networking/voting_handlers.go#363: Attempted to send a PullQuery message to a disconnected validator: N86eodVZja3GEyZJTo3DFUPGpxEEvjGHs

WARN [04-27|16:57:57] /networking/voting_handlers.go#363: Attempted to send a PullQuery message to a disconnected validator: DsMP6jLhi1MkDVc3qx9xx9AAZWx8e87Jd

WARN [04-27|16:57:57] /networking/voting_handlers.go#363: Attempted to send a PullQuery message to a disconnected validator: CMsa8cMw4eib1Hb8GG4xiUKAq5eE1BwUX

WARN [04-27|16:57:57] /networking/voting_handlers.go#363: Attempted to send a PullQuery message to a disconnected validator: N86eodVZja3GEyZJTo3DFUPGpxEEvjGHs

WARN [04-27|16:57:57] /networking/voting_handlers.go#363: Attempted to send a PullQuery message to a disconnected validator: EkKeGSLUbHrrtuayBtbwgWDRUiAziC3ao
`

It also overwhelms the log files removing any useful info. I would suggest either reducing the frequency of such messages to once a minute, and potentially give some useful stat like "disconnected validator last seen: X minutes, Y seconds ago".

**Comment by danlaine** [comment]
Resolved by #147
