### ISSUE TITLE
default db is created is relative and not always gecko/db

### ISSUE THREAD

**Issue by adasari** [ava-labs/gecko#112]
Default db should at gecko/db. Looks like it is not gecko/db all the time.

i am running node with go run main.go to understand the code and debug. i see db folder is created under gecko/main package.

<img width="415" alt="Screen Shot 2020-04-28 at 8 26 32 AM" src="https://user-images.githubusercontent.com/7031002/80506207-1e683900-892a-11ea-8f19-d0b9aa98579a.png">

**Comment by Determinant** [comment]
I think db will be created at the current working directory, right? @StephenButtolph If yes, then that's desired behavior.

**Comment by adasari** [comment]
@Determinant  Thanks for your response.

It shouldn't be relative to binary folder. binary can be run in any folder. data and logs folder are should be created always in fixed paths and not relative to current directory. thoughts ?

**Comment by Determinant** [comment]
I think we already have something on this: https://github.com/ava-labs/gecko/pull/115. :)
