### ISSUE TITLE
Snowman bootstrapping can be blocked with empty ids

### ISSUE THREAD

**Issue by bb-2** [ava-labs/gecko#117]
**Describe the bug**
Same as https://github.com/ava-labs/gecko/issues/94 but different application.
With Snowman, a validator can cause bootstrapping to hang in another node by responding to a Get request with the requested blkID and modified bytes that point to an empty parent. The bootstrapping node will be blocked as it searches for the nonexistent id,
`/snow/networking/sender/sender.go#87: Sending Get to validator NwEmCRVweJs9vTin7LpnweWSKVP4AB9Qi. RequestID: 10. ContainerID: 11111111111111111111111111111111LpoYY`

**To Reproduce**
Bootstrap a node and sendRequest for an unkown block to a validator running,
```
func (t *Transitive) Get(vdr ids.ShortID, requestID uint32, blkID ids.ID) {
    if blk, err := t.Config.VM.ModifiedGetBlock(blkID); err == nil {
	t.Config.Sender.Put(vdr, requestID, blkID, blk.Bytes())
    }
}
func (vm *VM) ModifiedGetBlock(id ids.ID) (snowman.Block, error) {
    blk, err := vm.state.Block(vm.baseDB, id)
    blk.parentID = ids.Empty
    blk.UpdateBytes()
    return &LiveBlock{ vm: vm, block: blk, }
}
func (b *Block) UpdateBytes() {
    codec := Codec{}
    bytes, _ := codec.MarshalBlock(b)
    b.bytes = bytes
}
```

**Expected behavior**
Derive the block id from the block bytes before working with the payload data

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by StephenButtolph** [comment]
Thanks for bringing this up.

To clarify you are saying that in a network with two nodes A, and B, if A sends a Get to B, then B can respond to this request with a block that doesn't match the requested block, right?

**Comment by bb-2** [comment]
That's correct. If during bootstrapping B responds to A with a block that doesn't match the requested block and that new block has a parent that doesn't exist, A will continually search for the nonexistent parent block as pending remains > 0.
