### ISSUE TITLE
Need error message for platform.importAVA when payerNonce missing or zero

### ISSUE THREAD

**Issue by michaelbnewman** [ava-labs/gecko#127]
**Describe the bug**
It is currently possible to use the "platform.importAVA" method without specifying the payerNonce parameter. This results in payerNonce set equal to zero by default, which the system will not allow, however a tx string is still passed back to the user which will not work with a subsequent "platform.issueTx" command.

**To Reproduce (assuming fresh keystore)**
`curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.importAVA",
    "params": {
        "username": "XXX",
        "password": "YYY",
        "to":"P_ADDRESS"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/P`

Correct would have been:
`curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.importAVA",
    "params": {
        "username": "XXX",
        "password": "YYY",
        "to":"P_ADDRESS",
        "payerNonce":1
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/P`

**Expected behavior**
The "platform.importAVA" method should have an error check and resulting error message to let the user know payerNonce has been forgotten or set to zero.

**Operating System**
Ubuntu 18.04.

**Additional context**
Issue was previously discussed with @StephenButtolph .

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Good point. Created #128 to address this and similar issues.
