### ISSUE TITLE
MacOS install ava-lab

### ISSUE THREAD

**Issue by CharlesGe129** [ava-labs/gecko#130]
**Describe the bug**
Can you please write a document about how Mac users should install ava-lab? I'm trying to follow the steps here [https://docs.ava.network/v1.0/en/quickstart/ava-getting-started/](url) and these are my issues: 

1. Package "github.com/decred/dcrd/dcrec/secp256k1" has been updated to "github.com/decred/dcrd/dcrec/secp256k1/v3", and some of your codes in "gecko/utils/crypto/secp256k1" need to be updated as well. 
2. After manually fixed point #1, I try to run "./scripts/build.sh", but got error "../../../../pkg/mod/github.com/ava-labs/salticidae-go@v0.1.0/crypto.go:4:11: fatal error: 'salticidae/crypto.h' file not found". I've installed "openssl" but I'm not sure if it contains "libssl-dev" and "libuv1-dev"

**To Reproduce**
Install ava-labs on MacOS.

**Comment by danlaine** [comment]
@CharlesGe129 Hi, thanks for submitting this.

Are you on the master branch? The messages you're getting seem like they're coming from the `go-mod-support` branch. What's the latest commit in your git history? (To check you can use `git log --oneline`)

**Comment by CharlesGe129** [comment]
@danlaine Thanks for your reply. 

Yes, I am on the master branch. The latest commit is "f257187941bfd87cbe7fb48b988fb7a73df8539d" and the commit message is "Merge pull request #124 from StephenButtolph/check-nil-account"

**Comment by danlaine** [comment]
@CharlesGe129 

What's your GOPATH (`echo $GOPATH`) and what is the path of the gecko directory?

Did you check out `go-mod-support` at any point?

**Comment by CharlesGe129** [comment]
@danlaine 
My GOPATH is "/Users/charlesge/go". 
The path of the gecko directory is "/Users/charlesge/go/src/github.com/ava-labs/gecko". 
I didn't check out ```go-mod-support``` at any point but I'm using "go mod" mode: ```GO111MODULE="on"```. Should I use vendor mode?

**Comment by danlaine** [comment]
@CharlesGe129 Ah ok the master branch does not support go modules yet (though we're adding that soon.) Try turning off `GO111MODULE` and try again.

Also, make sure you're on Go 1.13

**Comment by CharlesGe129** [comment]
@danlaine Thanks for your help. 

I end up using ubuntu to build a docker image, and it works. But I have a follow-up question. How can I deploy a smart contract on ava-lab test net? I didn't find any documentation or tutorial about that. Can you please provide a tutorial? Thanks in advance.

**Comment by CharlesGe129** [comment]
I use ```avm.createAddress``` to create address, then use web3 to link to the endpoint ```127.0.0.1:9650/ext/bc/C/rpc ```. But web3 said that I don't have any addresses/accounts. Why is that?

**Comment by danlaine** [comment]
@CharlesGe129 Glad you got your installation working. I'm going to close this issue. 
As for your questions: hop on our Discord server and we can help you there. 
Or, if you don't want to create a Discord account, you can email me at daniel.laine@avalabs.org
