### ISSUE TITLE
node isn't stopped when port is busy

### ISSUE THREAD

**Issue by adasari** [ava-labs/gecko#131]
when default api server port is busy, node is still running and not gracefully reporting error and stopping the node to start as rest apis wont respond.

Steps to reproduce
1. run a process on default port (9650) 
2. run ava node (./build/ava)

Expected behavior:
should report an error and stop the node.

**Comment by danlaine** [comment]
Can you clarify this a bit?
Are you saying that when your node stops, the staking port remains occupied?
Or that your node doesn't respond to `ctrl + c` ?
Or something else?

**Comment by adasari** [comment]
when http port (any port that is used by node) is busy, ideally node should terminate. node is trying to connect to peers and http endpoints are not working as api server is not up.

**Comment by danlaine** [comment]
The node does should terminate if, when it starts, the HTTP or staking port are in use.
You're saying it's not terminating?
Can you provide some logs or screenshots, please?

**Comment by StephenButtolph** [comment]
@danlaine If the HTTP server fails to be started, then the node will run without access to the HTTP server. @adasari , working to resolve this.

The relevant code is: https://github.com/ava-labs/gecko/blob/master/node/node.go#L474-L485

**Comment by adasari** [comment]
@StephenButtolph yes. i was referring to same code. the same case applies in case of TLS as well. there should be clear error root cause i.e files not found vs invalid cert files vs some other error. At the moment, i couldn't see the differentiation. HTH.

**Comment by adasari** [comment]
I can raise PR if you like.

**Comment by StephenButtolph** [comment]
Thanks for raising this issue, we've been pretty swamped with stability fixes. But things are starting to calm down a bit, so I was able to take a stab at this.
