### ISSUE TITLE
avm.getAllBalances method does not work

### ISSUE THREAD

**Issue by erknfe** [ava-labs/gecko#137]
**Describe the bug**  
when I trying to run avm.GetAllBalances method I got this message:  
rpc: can't find method "avm.getAllBalances"  
  
**Screenshots**  
![er1](https://user-images.githubusercontent.com/7534459/81176112-5405c580-8fad-11ea-8a1b-88a3509797db.PNG)  
  
  
By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Resolved on discord...user didn't have most recent code

**Comment by erknfe** [comment]
after update gecko getAllBalance problem is continue.

**Comment by danlaine** [comment]
@erknfe Are you still facing this issue? Can you reproduce it?

**Comment by erknfe** [comment]
@danlaine I tested it again and the result is like this:  
  
`git pull` and `./script/build.sh`  
![git-pull](https://user-images.githubusercontent.com/7534459/81700461-59618500-9471-11ea-85cb-c5f511770919.PNG)  
  
`sh keys/genStaker.sh` and `./build/ava`  
![run-node](https://user-images.githubusercontent.com/7534459/81700468-5b2b4880-9471-11ea-99a8-abdc24718ed9.PNG)  
  
`git log --oneline`
![check-git](https://user-images.githubusercontent.com/7534459/81700477-5cf50c00-9471-11ea-9093-1bcf3e6e9824.PNG)  
  
problem is continue
![problem](https://user-images.githubusercontent.com/7534459/81700479-5d8da280-9471-11ea-9ae4-3bd27ef136bf.PNG)

**Comment by danlaine** [comment]
@erknfe Can you please pull the latest code, re-build and try again?

**Comment by erknfe** [comment]
After fress install, problem is solved on my side.  

![er1](https://user-images.githubusercontent.com/7534459/82155799-23147300-9880-11ea-8f94-a36b8376ee88.PNG)
