### ISSUE TITLE
avm.CreateAddress not working

### ISSUE THREAD

**Issue by kushptlapigarage** [ava-labs/gecko#139]
**Describe the bug**
avm.createAddress not working

**To Reproduce**
Follow *Getting Started*.
Run Gecko with /build/ava
Run sh keys/genStaker.sh
Run 
```
curl -X POST --data '{
>      "jsonrpc": "2.0",
>      "id": 1,
>      "method": "avm.createAddress",
>      "params": {
>          "username": "testuser",
>          "password": "pass"
>      }
> }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/keystore
```

Response `{"jsonrpc":"2.0","error":{"code":-32000,"message":"rpc: can't find service \"avm.CreateAddress\"","data":null},"id":1}`

**Expected behavior**
Some sort of retuning of address

**Operating System**
Mac OS

**Additional context**
* Can I fire curl command from anywhere or it has to be from specific location ?
* Can I fire curl command with same username multiple times ?
* What are the list of errors and descriptions ?

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by kushptlapigarage** [comment]
```$ go version
go version go1.13 darwin/amd64
```

**Comment by danlaine** [comment]
@kushptlapigarage Hi, thanks for taking the time to submit an issue.
This problem is occurring because the test network is down, and your node is unable to bootstrap into the network.
We will work to improve the user experience and messaging so this is more obvious in the future.
