### ISSUE TITLE
warning: ‘Z’ directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=

### ISSUE THREAD

**Issue by rfikki** [ava-labs/gecko#14]
**Describe the bug**
github.com/ava-labs/go-ethereum/accounts/usbwallet/trezor
github.com/ava-labs/go-ethereum/p2p
# github.com/ava-labs/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
duk_logging.c: In function ‘duk__logger_prototype_log_shared’:
duk_logging.c:184:64: warning: ‘Z’ directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=]
  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
                                                                ^
In file included from /usr/include/stdio.h:862,
                 from duk_logging.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 25 and 85 bytes into a destination of size 32
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
no error

**Operating System**
WSL - Ubuntu 18.04


By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by swdee** [comment]
The upstream bug report for this is here https://github.com/svaarala/duktape/issues/2137

**Comment by moreati** [comment]
I think the bug is actually in the Go bindings for duktape: https://github.com/olebedev/go-duktape.v3, specifically fixed by https://github.com/olebedev/go-duktape/pull/67, and https://github.com/ethereum/go-ethereum/pull/20777. Awaiting approval or feedback on https://github.com/ava-labs/go-ethereum/pull/1 to incorporate the fix into Avalab's vendored version

**Comment by StephenButtolph** [comment]
[ava-labs/go-ethereum#1](https://github.com/ava-labs/go-ethereum/pull/1) was merged, there are still warning relating to the duktape repo, but the overflow warning has been fixed.

**Comment by moreati** [comment]
For the record, the remaining warning I see is

```
# github.com/ava-labs/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
```
