### ISSUE TITLE
Suggestion for node install documentation

### ISSUE THREAD

**Issue by greggdourgarian** [ava-labs/gecko#140]
**Describe the bug**
The install doc mentions Go at the beginning but never includes a step in the step-by-step to verify you have the correct version installed.

**To Reproduce**
Follow exact steps delineated in the documentation file on a virgin Ubuntu server.  Fails because default Go version installed is not the current one recommended.

**Expected behavior**
Installation successful

**Screenshots**

**Operating System**
Ubuntu 18.04.3 (LTS) x64

**Additional context**
Otherwise a very easy install!

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Thanks for the feedback @greggdourgarian 
We'll make this more explicit in the docs

**Comment by danlaine** [comment]
@greggdourgarian The [quickstart](https://docs.ava.network/v1.0/en/quickstart/ava-getting-started/) now specifies how to check that your Go version is correct. Thanks again.
