### ISSUE TITLE
Feature: Add `P-` prefix to P-Chain addresses

### ISSUE THREAD

**Issue by danlaine** [ava-labs/gecko#161]
Addresses on the P-Chain should be prefixed with `P-`, just as X-Chain addresses are prefixed with `X-` and C-Chain with `C-`

**Comment by moreati** [comment]
While we're namespacing things, how about `N-` for a node id?

**Comment by moreati** [comment]
I'm taking a stab at adding `P-` aliases. Assumptions/design decisions
- Returned addresses will always have a `P-` prefix
- Address are accepted with or without `P-` prefix

**Comment by moreati** [comment]
@danlaine ping. Are P- prefixes for P-Chain addresses something you still want? Broadly, is my prototype worth continuing.

**Comment by danlaine** [comment]
@moreati  Hello! Thanks for your PR (as always), and sorry for the delay in responding to it.

Yes, this is definitely something we still want. Per your above comment, I think it would be best if the prefix (`P-`) is always included for the sake of consistency.
