### ISSUE TITLE
node issue after 2 min of running

### ISSUE THREAD

**Issue by AlexDCryptoC** [ava-labs/gecko#162]
I just started from scratch today and my node stopped after 2 min of running. Please check the below printscreen. 

Even if you reboot your machine or your screen session and restart the node, the problem comes up again within 2 min from launching.

Thanks!

![ava error](https://user-images.githubusercontent.com/18679675/81822592-fee12b00-953b-11ea-808e-16980734b34b.JPG)

**Comment by danlaine** [comment]
Hi @AlexDCryptoC thanks for reporting.
What OS are you using?
What version of go are you using? Run `go version` to find out.

**Comment by AlexDCryptoC** [comment]
ubuntu 18.04
go version go1.13 linux/amd64
19db6fe6d54dd138d9fb19908878e8015df05f9d

**Comment by swdee** [comment]
Sounds like a `ulimit` problem.  Read the following link to see if it solves your issue;

https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a

**Comment by AlexDCryptoC** [comment]
Hei. Thanks for link but still i have the same issue after i followed each step described there. 
![still](https://user-images.githubusercontent.com/18679675/81913402-998f4780-95d8-11ea-8b24-aef7269b9028.JPG)

**Comment by danlaine** [comment]
@AlexDCryptoC Looks like this is a different, known error.
Sometimes when a node crashes, the staking port remains occupied.
Try running the node again, but do `--staking-port=10000` (or some other empty port).

**Comment by AlexDCryptoC** [comment]
nope, still doesn't work

**Comment by danlaine** [comment]
@AlexDCryptoC Same problem? Different problem?

**Comment by AlexDCryptoC** [comment]
Ya the behavior was the same, but after i reinstalled everything from scratch on another machine with go version go1.14 linux/amd64 , i could manage to start the node and create the validator as well.

I'll close this issue.

Thank you for support.
