### ISSUE TITLE
Snowball finalization threshold is off by 1

### ISSUE THREAD

**Issue by bb-2** [ava-labs/gecko#17]
**Describe the bug**
The Snowball and Snowflake finalization threshold is off by 1.

<img width="387" alt="Screen Shot 2020-03-14 at 10 52 26 AM" src="https://user-images.githubusercontent.com/43212522/76684945-51f33c00-65e6-11ea-84cb-89eb48cbcef0.png">

```
sf.finalized = (!sf.rogue && sf.confidence >= sf.betaVirtuous) ||
		sf.confidence >= sf.betaRogue
```
https://github.com/ava-labs/gecko/blob/master/snow/consensus/snowball/nnary_snowflake.go#L66

**Expected behavior**
```
sf.finalized = (!sf.rogue && sf.confidence > sf.betaVirtuous) ||
		sf.confidence > sf.betaRogue
```

**Operating System**
Universally applicable.

**Comment by StephenButtolph** [comment]
Thanks for looking into this! The paper actually defines `beta` as the number of consecutive successful rounds needed to commit the decision, so the implementation is correct here. When the paper is next updated, it will have fixed this inconsistency in the pseudocode.
