### ISSUE TITLE
too many open files; retrying in 1s

### ISSUE THREAD

**Issue by AlexDCryptoC** [ava-labs/gecko#175]
Hei,

After 5 min of running, the node brings me this error and i can not stop or restart it anymore. 

![image](https://user-images.githubusercontent.com/18679675/82467448-59ddc980-9aca-11ea-8720-0365026b5e1e.png)

Thank you

**Comment by danlaine** [comment]
Thanks for reporting @AlexDCryptoC 
lookng into this

**Comment by tbrunain** [comment]
Having the same issue here . It happened few hours after I started my node.

**Comment by tbrunain** [comment]
Got it again, this time I checked number of open file (with `lsof | grep -w "ava" | wc -l`) before and after the issue : 

- Before it's around 1100
- After 16600 !

I was not doing specific stuff, just calling api endpoints. (metrics, X, P, Keystore ...)

**Comment by AlexDCryptoC** [comment]
defiantly this is a bug that should be solved asap.

**Comment by danlaine** [comment]
Hi @tbrunain @AlexDCryptoC 

You're right -- this is a nasty bug, and we're working on fixing it.
We run the EVM in a separate process using hashicorp's go-plugin library, and this bug is coming from there. Sorry about this :(

**Comment by danlaine** [comment]
@AlexDCryptoC Have you had this issue since Denali release? If not, will close the issue.

**Comment by tbrunain** [comment]
On my side it looks fine, I've been monitoring it since Monday and :

![image](https://user-images.githubusercontent.com/29312251/83642093-b05d0480-a5ae-11ea-9988-2215900fa5b1.png)

**Comment by AlexDCryptoC** [comment]
I got no time to join Denali :( but i think we can close this issue atm. Also for me until yesterday everything worked fine
