### ISSUE TITLE
i can not query anymore getBalance of a wallet or charge a pChain account via  fund method

### ISSUE THREAD

**Issue by AlexDCryptoC** [ava-labs/gecko#181]
404 page not found

![image](https://user-images.githubusercontent.com/18679675/82882713-21b30c80-9f4a-11ea-90df-5aa716d3af68.png)

**Comment by danlaine** [comment]
This looks like your node wasn't done bootstrapping when you called these API methods...how long had your node been running?

**Comment by AlexDCryptoC** [comment]
more than 4 hours atm but i think there also is a problem with my node . Please check the below printscreen
![image](https://user-images.githubusercontent.com/18679675/82901612-dbb87180-9f66-11ea-9ec3-5d8ea5ac9b66.png)

**Comment by AlexDCryptoC** [comment]
problem solved after i successfully upgraded to the latest version
