### ISSUE TITLE
Can't Shutdown Ava

### ISSUE THREAD

**Issue by joesixpack** [ava-labs/gecko#187]
![image](https://user-images.githubusercontent.com/23145642/82974960-0965e080-9f90-11ea-9ad9-87feae557b80.png)

**Comment by danlaine** [comment]
Hi, thanks for reporting @joesixpack 
What commit are you on? Run `git rev-parse HEAD` to find out.

**Comment by joesixpack** [comment]
f7efc0c6b42194768187222db57a5dd06657a77a

**Comment by aaronbuchwald** [comment]
Thanks for letting us know about the issue @joesixpack . Working on trying to reproduce and solve this now. How long are you running your node for before trying to shut down?

**Comment by joesixpack** [comment]
Time varied.  It never shuts down so I have to kill the process.  I'm running it via screen.
