### ISSUE TITLE
platform.validates returns "'subnetID' not specified" even though subnetID is correctly passed

### ISSUE THREAD

**Issue by zefonseca** [ava-labs/gecko#193]
**Describe the bug**

Calling platform.validates incorrectly returns "'subnetID' not specified" error.

platformvm/service.go, line 1336

```
	case args.SubnetID.Equals(ids.Empty):
		return errors.New("'subnetID' not specified")
	}

```
**To Reproduce**

```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.validates",
    "params":{
        "subnetID":"11111111111111111111111111111111LpoYY"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/P

{"jsonrpc":"2.0","error":{"code":-32000,"message":"'subnetID' not specified","data":null},"id":1}

```

Commit:

```
git rev-parse HEAD
f7efc0c6b42194768187222db57a5dd06657a77a

```
**Expected behavior**
Should return list of blockchainID's

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Great catch, thanks for bringing it to our attention @zefonseca . Working on a fix rn

**Comment by aaronbuchwald** [comment]
Thanks again for pointing this out, this bug has been patched
