### ISSUE TITLE
unable to build ava 

### ISSUE THREAD

**Issue by nlpvan-paul** [ava-labs/gecko#197]
**Describe the bug**
I did pull the latest today - 05-31/2020 from git clone https://github.com/ava-labs/gecko.git

- issue1 - initially I did build on ununtu 20.04 the build exits with something like missing 'miliseconds'

- issue2 - I did switch to ubuntu 18.04; and did pull from git; the build can not start - script  exits with:
-----------
Downloading dependencies...
go: unknown subcommand "mod"
Run 'go help' for usage.
------------

- issue3 - I did remove the ubuntu18.04 go install, did download current - go1.14.3.linux-amd64.tar.gz
after starting - build.sh    I get -
----------
Downloading dependencies...
github.com/tjfoc/gmsm@v1.3.0: verifying module: checksum mismatch
	downloaded: h1:qhgkrZru95jFP9NbVPknJvc9vgkMXhOEzkOASKdc0oQ=
	sum.golang.org: h1:i7c6Za/IlgBvnGxYpfD7L3TGuaS+v6oGcgq+J9/ecEA=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
----------

**To Reproduce**
pull - git clone https://github.com/ava-labs/gecko.git
and build on ubuntu 18.04 and 20.04

**Expected behavior**
build successfully

**Screenshots**
...

**Operating System**
ubuntu 20.04 , ubuntu 18.04

**Additional context**
...

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@nlpvan-paul I'm pretty sure you're not running Go >= 1.13

Can you do `go version` to check? Thanks

**Comment by nlpvan-paul** [comment]
Currently I use the latest go - go1.14.3.linux-amd64.tar.gz 
The message is the same when I build on wither ubuntu 18.04 or ubunty 20.04
Did you actually try building the 05.31 release?

    On Wednesday, June 3, 2020, 6:20:41 AM PDT, danlaine <notifications@github.com> wrote:  
 
 


@nlpvan-paul I'm pretty sure you're not running Go >= 1.13

Can you do go version to check? Thanks

**Comment by danlaine** [comment]
Hi @nlpvan-paul are you still having this issue?

**Comment by nlpvan-paul** [comment]
Hi Daniel,I did give up trying to build the 05.31 release ava with source and am using the gecko binaries.If you did release anything newer - let me know .Paul.

    On Tuesday, June 9, 2020, 9:11:33 AM PDT, danlaine <notifications@github.com> wrote:  
 
 


Hi @nlpvan-paul are you still having this issue?

**Comment by danlaine** [comment]
@nlpvan-paul 
Latest release is 0.5.4
Hopefully it gives a smoother experience. Let me know how it goes.

**Comment by danlaine** [comment]
Closing this for now. Let me know if you're still having this issue.

**Comment by nlpvan-paul** [comment]
Hi,
I did switch to other projects. I just did download 0.5.7 release and will find time to test. If issues still present I will report it.Paul.




    On Wednesday, June 24, 2020, 12:37:36 PM PDT, danlaine <notifications@github.com> wrote:  
 
 


Closed #197.
