### ISSUE TITLE
API getSubnets should return default subnet

### ISSUE THREAD

**Issue by strictlymomo** [ava-labs/gecko#200]
**Describe the bug**
Endpoint currently returns subnets sans default subnet.

**Expected behavior**
Include default subnet in response.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Fixed
