### ISSUE TITLE
macOS OSX 10.15.5  stuck at INFO [06-01|22:10:36] /api/server.go#105: adding route /ext/bc/11111111111111111111111111111111LpoYY

### ISSUE THREAD

**Issue by paulainsley** [ava-labs/gecko#201]
when running a node export PATH=$PATH:/usr/local/go/bin

go version

cd go/src/github.com/ava-labs/gecko git pull && bash ./scripts/build.sh
./build/ava
gets stuck at this log, this is new  before  i updated my mac node was working fine.
By submitting this issue I agree to the [Terms and Conditions]INFO [06-01|22:10:36] /api/server.go#105: adding route /ext/bc/11111111111111111111111111111111LpoYY

**Comment by aaronbuchwald** [comment]
Thanks for reporting this here Paul, do you have a full screenshot of the logs that you saw?

**Comment by paulainsley** [comment]
problem resolved, downloaded binary from
https://github.com/ava-labs/gecko/releases  launched it and problem solved,
bootstrap  instant!! also had issue with network upgrading from network 2
to 3.

 this also solved my problem, mange to get my node done under 15 minutes.
  thanks
