### ISSUE TITLE
ipcs.publishBlockchain is mixing up blockchainID and subnetID

### ISSUE THREAD

**Issue by zefonseca** [ava-labs/gecko#203]
When calling ipcs.publishBlockchain with a valid blockchainID it returns an error. Passing a subnetID is accepted.

Either the API documentation and parameter name should be changed to accept subnetID or this is a bug.

To Reproduce:

```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getBlockchains",
    "params":{

    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/P
```

Returns:

`{"jsonrpc":"2.0","result":{"blockchains":[{"id":"4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM","name":"X-Chain","subnetID":"11111111111111111111111111111111LpoYY","vmID":"jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq"},{"id":"2mUYSXfLrDtigwbzj1LxKVsHwELghc5sisoXrzJwLqAAQHF4i","name":"C-Chain","subnetID":"11111111111111111111111111111111LpoYY","vmID":"mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6"},{"id":"q8CVPqtVEXanDTuU1GnPngLRXVW1WD7XTQi8JVVaJsXgnZDVW","name":"Simple DAG Payments","subnetID":"11111111111111111111111111111111LpoYY","vmID":"sqjdyTKUSrQs1YmKDTUbdUhdstSdtRTGRbUn8sqK8B6pkZkz1"},{"id":"pUASyygGd8XyCgzeP9KC1GAiZ4Qjycq6fs2HfphA6vSFbvLe6","name":"Simple Chain Payments","subnetID":"11111111111111111111111111111111LpoYY","vmID":"sqjchUjzDqDfBPGjfQq2tXW1UCwZTyvzAWHsNzF2cb1eVHt6w"},{"id":"2kKSkL4vgVR6QSknoKprsGHVHiEbf7WiGEeSuJUGoB3WzeBhce","name":"Simple Timestamp Server","subnetID":"11111111111111111111111111111111LpoYY","vmID":"tGas3T58KzdjLHhBDMnH2TvrddhqTji5iZAMZ3RXs2NLpSnhH"},{"id":"AQYsrED3qxEVovrRqEYhA5YDMXBhPD3H1spF5SMTbyT13z6oH","name":"My new AVM","subnetID":"PFDKjhGzqdNm9D2u7pkhW8xwRGVjuxjCZ5YQGd71vVj2Rgx9i","vmID":"jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq"}]},"id":1}`

Choose any valid blockchain ID, such as the X-Chain ID `4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM` and call `ipcs.publishBlockchain` using it:

```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "ipcs.publishBlockchain",
    "params":{
	"blockchainID": "4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/ipcs
```

Which results in error:

`{"jsonrpc":"2.0","error":{"code":-32000,"message":"there is no ID with alias 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM","data":null},"id":1}
`
But if we try using a subnetID, it works. From the blockchain listing, use the first listed subnetID 11111111111111111111111111111111LpoYY :

```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "ipcs.publishBlockchain",
    "params":{
	"blockchainID": "11111111111111111111111111111111LpoYY"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/ipcs
```

Which is successful:

`{"jsonrpc":"2.0","result":{"url":"ipc:///tmp/11111111111111111111111111111111LpoYY.ipc"},"id":1}
`
So the command is accepting subnetID's, not blockchainID's.

**Operating System**

`Linux 5.3.0-55-generic #49-Ubuntu SMP Thu May 21 12:47:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`

Additional context

gecko commit:

```
commit 7671cab97260ab2eebd8b29f98b23e219da25a20 (HEAD -> master, tag: v0.5.0, origin/master, origin/HEAD)
Merge: f7efc0c d384051
```

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for reporting this @zefonseca , I'm looking into it now. Do you know if your node had finished bootstrapping when you ran this?

**Comment by zefonseca** [comment]
> Thanks for reporting this @zefonseca , I'm looking into it now. Do you know if your node had finished bootstrapping when you ran this?

Hi Aaron. Yes, the node is in full operation. 

I can replicate it any time on 2 running nodes.

Just tested on 0.5.1 as well, bug still there.

**Comment by aaronbuchwald** [comment]
The subnet ID 11111111111111111111111111111111LpoYY is also the blockchain id for the platform chain. So it looks like it's being interpreted correctly as a blockchain ID and that's what the API expects and uses. The platform chain bootstraps first and that's why it works when the others don't. I was able to reproduce it, but once my node was bootstrapped the problem went away after the new blockchain IDs were added. Could you add screenshots of the logs from gecko when you are sending the query that fails?

**Comment by zefonseca** [comment]
TIL that the P-Chain ID is the same as its subnet. Thanks.

I get these messages on the log console when trying to export the blockchains: 

```
ERROR[06-03|22:18:59] /api/ipcs/server.go#66: unknown blockchainID: there is no ID with alias 2MPPHSGYkzNCoXvumCTbMq6cCW1FEzUsCgAfpwwE9B74DuTvkF

ERROR[06-03|22:21:36] /api/ipcs/server.go#66: unknown blockchainID: there is no ID with alias SvKVRLxwZ91tBX6bMnZeAgY4iVrY6zFFhE9oPtChoQ2yqugVL
```

I just noticed something. I can export blockchains validated by `11111111111111111111111111111111LpoYY` subnet but not the blockchains created by users.

Are only the default blockchains, validated by the default chain, supposed to be exported to IPC?

**Comment by zefonseca** [comment]
OK, I wrote a script to try all blockchains. Here's the output:

```
{'id': 'rrEWX7gc7D9mwcdrdBxBTdqh1a7WDVsMuadhTZgyXfFcRz45L', 'name': 'X-Chain', 'subnetID': '11111111111111111111111111111111LpoYY', 'vmID': 'jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq'}
{'url': 'ipc:///tmp/rrEWX7gc7D9mwcdrdBxBTdqh1a7WDVsMuadhTZgyXfFcRz45L.ipc'}

{'id': 'zJytnh96Pc8rM337bBrtMvJDbEdDNjcXG3WkTNCiLp18ergm9', 'name': 'C-Chain', 'subnetID': '11111111111111111111111111111111LpoYY', 'vmID': 'mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6'}
{'url': 'ipc:///tmp/zJytnh96Pc8rM337bBrtMvJDbEdDNjcXG3WkTNCiLp18ergm9.ipc'}

{'id': '1GHaaPbg1YBR4qiATuFNfL2j9StJwmddwXiwm1s9ts5KXvMai', 'name': 'Simple DAG Payments', 'subnetID': '11111111111111111111111111111111LpoYY', 'vmID': 'sqjdyTKUSrQs1YmKDTUbdUhdstSdtRTGRbUn8sqK8B6pkZkz1'}
{'url': 'ipc:///tmp/1GHaaPbg1YBR4qiATuFNfL2j9StJwmddwXiwm1s9ts5KXvMai.ipc'}

{'id': 'jV7eZZh6Y2a35aaMLUGwBN1g2PNqfuuxLTSHu98EpHyPJDcQJ', 'name': 'Simple Chain Payments', 'subnetID': '11111111111111111111111111111111LpoYY', 'vmID': 'sqjchUjzDqDfBPGjfQq2tXW1UCwZTyvzAWHsNzF2cb1eVHt6w'}
{'url': 'ipc:///tmp/jV7eZZh6Y2a35aaMLUGwBN1g2PNqfuuxLTSHu98EpHyPJDcQJ.ipc'}

{'id': 'am6cZ3MqzsbJG5mhNvrX2Z3w5uzRxZtgEacwhNqQ5p5KHAhtM', 'name': 'Simple Timestamp Server', 'subnetID': '11111111111111111111111111111111LpoYY', 'vmID': 'tGas3T58KzdjLHhBDMnH2TvrddhqTji5iZAMZ3RXs2NLpSnhH'}
{'url': 'ipc:///tmp/am6cZ3MqzsbJG5mhNvrX2Z3w5uzRxZtgEacwhNqQ5p5KHAhtM.ipc'}

{'id': '2MPPHSGYkzNCoXvumCTbMq6cCW1FEzUsCgAfpwwE9B74DuTvkF', 'name': 'My Denali Private Subnet AVM', 'subnetID': '21Zg8zBbWtFg5G4fz49DZzsBoSf1UdRqXGxxCwrhzJSw1Q5aqr', 'vmID': 'jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq'}
there is no ID with alias 2MPPHSGYkzNCoXvumCTbMq6cCW1FEzUsCgAfpwwE9B74DuTvkF
None

{'id': '2oTXV5A53VKm9skCLtxWNfYRaKrTBz2mHmqxTEjdxoddXBeqNf', 'name': 'My Denali Public Subnet AVM', 'subnetID': 'MSRkCSB8etc3eyJpxAxojCi1rGDsYG1WNBQME2FA2K5Rx5GTq', 'vmID': 'jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq'}
there is no ID with alias 2oTXV5A53VKm9skCLtxWNfYRaKrTBz2mHmqxTEjdxoddXBeqNf
None

{'id': 'uL545xxgXgKBSoysaPiwt2q7hxMuE44GBs68g5mhSPbgcWd1A', 'name': 'Denali Single Validator AVM', 'subnetID': 'LvhHvWZjPZ9fYVb5WdyLpMiqejwjNXNFmAA32jp9dBCAKZYkX', 'vmID': 'jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq'}
there is no ID with alias uL545xxgXgKBSoysaPiwt2q7hxMuE44GBs68g5mhSPbgcWd1A
None

{'id': 'SvKVRLxwZ91tBX6bMnZeAgY4iVrY6zFFhE9oPtChoQ2yqugVL', 'name': 'Denali Single Validator AVM 2', 'subnetID': 'LvhHvWZjPZ9fYVb5WdyLpMiqejwjNXNFmAA32jp9dBCAKZYkX', 'vmID': 'jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq'}
there is no ID with alias SvKVRLxwZ91tBX6bMnZeAgY4iVrY6zFFhE9oPtChoQ2yqugVL
None
```

This seems to confirm that only blockchains validated by the default subnet can be exported.

Is this by design?

**Comment by aaronbuchwald** [comment]
Could you check to see if your node is validating those blockchains? You can run the call getBlockchainStatus in the platform API to check: https://github.com/ava-labs/docs/blob/master/docs/v1.0/en/api/platform.md

**Comment by zefonseca** [comment]
Just checked, it's not validating those chains.

**Comment by aaronbuchwald** [comment]
@zefonseca You'll need to add your node as a validator on those blockchains in order to publish them

**Comment by zefonseca** [comment]
OK thanks. Maybe this could be included in documentation? Closing the issue now.
