### ISSUE TITLE
Feature request: `ava -version` to show version that is running

### ISSUE THREAD

**Issue by moreati** [ava-labs/gecko#206]
It would be nice to add a `-version` option to the ava node software, so it's easy to tell what version is installed. Ideally it will show a version like `0.5.0`, but as a first stab just the git revision used to build it would be helpful.

I'll try to submit a PR this weekend.

**Comment by gin** [comment]
@moreati May I steal this task from you, please?

I am relatively new to using Go, and would like to improve. Maybe you can comment on how the code can be improved after the PR? I think I can have it done by Saturday morning. 😀

**Comment by danlaine** [comment]
I actually just made a pr for this:
https://github.com/ava-labs/gecko/pull/216

**Comment by gin** [comment]
👍 So quick. lol

**Comment by danlaine** [comment]
Resolved by https://github.com/ava-labs/gecko/pull/228
