### ISSUE TITLE
using RAM 71%

### ISSUE THREAD

**Issue by qnixAVA** [ava-labs/gecko#210]
hello, i build NODE on Ubuntu application from windows, 
i did this 2days ago 
During these 2 days, that was all good, but i wake up this morning and my node using 71% of my pc RAM,
i let him, during this time i search any solution, after ~1hour, my node crashed, and my RAM came back to normal

Finally I had to restart my node  but now my uptime isnt really :(
![photo_2020-06-04_11-30-34](https://user-images.githubusercontent.com/66427226/83769047-abb45100-a67f-11ea-92cb-267c1ddbdcda.jpg)

**Comment by aaronbuchwald** [comment]
Hey @qnixAVA thanks for reporting the issue, would you mind sharing more details about your exact setup? Did you run this on virtual box on a windows computer, could you describe your exact setup? Would you mind also sharing any logs produced during the run? You can find the log directory in HOME/.gecko/logs.

**Comment by qnixAVA** [comment]
Hello, I run AVA on Ubuntu WSL and my computer got 8go RAM
And so I just manually reboot my node, thats work

Le ven. 5 juin 2020 à 20:28, aaronbuchwald <notifications@github.com> a
écrit :

**Comment by aaronbuchwald** [comment]
Thank you @qnixAVA , would you mind also sharing any of the logs produced during the run that ended up using 71% of available RAM, so that we can try to diagnose and fix the issue and improve your UX?
