### ISSUE TITLE
avm.importKey    returns - 404 page not found

### ISSUE THREAD

**Issue by nlpvan-paul** [ava-labs/gecko#217]
**Describe the bug**
curl --location --request POST '127.0.0.1:9650/ext/bc/X' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "id"     :3,
    "method" :"avm.importKey",
    "params" :{
        "username":"YOUR USERNAME HERE",
        "password":"YOUR PASSWORD HERE",
        "privateKey":"ewoqjP7PxY4yr3iLTpLisriqt94hdyDFNgchSxGGztUrTXtNN"
    }
}'

returns - 404 page not found

**To Reproduce**
The sequence of calls is -

    // create user

    ret = create_usr(fct_id,fct_pw);
   
   // createAddress
    ret = mk_adr(fct_id,fct_pw);
//    printf("\n faucet adr - %s", fct_adr);     fflush(stdout);
   
    // get balance in faucet addr
   ret = get_balnc("AVA", fct_adr);

    // if no funds - import key and send to
    ret = imprt_key(fct_key, fct_id,fct_pw);     <<<--- 404 page not found

**Expected behavior**
return json ok string

**Screenshots**
...

**Operating System**
ubuntu 18.04 ,20.04

**Additional context**
I  do testing in a local network of nodes when the ava daemon is strated as -

./ava ... --network-id=local ... 

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by tzarebczan** [comment]
I was also seeing this the first time I launched, but it worked after restarting the daemon. In my case it was for avm.createAddress: 
```curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :2,
    "method" :"avm.createAddress",
    "params" :{
        "username": "x",
        "password": "x!"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
```

**Comment by nlpvan-paul** [comment]
Hello Thomas,I did try importing key multiple times - again and again it is failing.
The sequence of commands include creating a user , using pre-created and/or newly created address, getting balance and then import key...
The same behavior is on - ava testnet and ava -local daemon. I use the binary of the 05/31 'denali' release on ubuntu 20.04 .

Paul.


    On Friday, June 5, 2020, 8:27:27 PM PDT, Thomas Zarebczan <notifications@github.com> wrote:  
 
 


I was also seeing this the first time I launched, but it worked after restarting the daemon. In my case it was for avm.createAddress:
    "jsonrpc":"2.0",
    "id"     :2,
    "method" :"avm.createAddress",
    "params" :{
        "username": "x",
        "password": "x!"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X

**Comment by danlaine** [comment]
@nlpvan-paul @tzarebczan 
Hi, this is probably happening because your node's X-Chain is not yet bootstrapped.
When it is done bootstrapping (in the newest release) it will print:
`INFO [06-09|13:26:09] <X Chain> /snow/engine/avalanche/transitive.go#80: bootstrapping finished with 1 vertices in the accepted frontier`

Try running a node with the latest version (0.5.4 at the moment), waiting until it's bootstrapped (< 30 minutes) and trying again to issue API calls.

Let me know how that goes.
Thanks for reporting and for your patience! :)

**Comment by nlpvan-paul** [comment]
hi,
the node did actually bootstrap but I use 0.5.0 release.please keep notifying us on new releases.I will download and check 0.5.4 release.
paul.

    On Tuesday, June 9, 2020, 10:31:15 AM PDT, danlaine <notifications@github.com> wrote:  
 
 


@nlpvan-paul @tzarebczan
Hi, this is probably happening because your node's X-Chain is not yet bootstrapped.
When it is done bootstrapping (in the newest release) it will print:
INFO [06-09|13:26:09] <X Chain> /snow/engine/avalanche/transitive.go#80: bootstrapping finished with 1 vertices in the accepted frontier

Try running a node with the latest version (0.5.4 at the moment), waiting until it's bootstrapped (< 30 minutes) and trying again to issue API calls.

Let me know how that goes.
Thanks for reporting and for your patience! :)

**Comment by danlaine** [comment]
Hi @nlpvan-paul are you still facing this issue after bootstrapping when running the most recent release?

**Comment by nlpvan-paul** [comment]
Hi,
I did switch to other projects. I just did download 0.5.7 release and will find time to test. If issues still present I will report it.Paul.

    On Wednesday, June 24, 2020, 12:30:34 PM PDT, danlaine <notifications@github.com> wrote:  
 
 


Hi @nlpvan-paul are you still facing this issue after bootstrapping when running the most recent release?

**Comment by danlaine** [comment]
Ok, going to close this for now. Let me know if you have any issues going forward
