### ISSUE TITLE
Txn remains pending for a local test network of 3 nodes

### ISSUE THREAD

**Issue by slniko11** [ava-labs/gecko#225]
**Describe the bug**
While performing a transaction on a local test network of 3 nodes(with staking disabled) on the latest denali release code, the transaction remains pending.

**To Reproduce**
1) Launch a 3 node local test network(staking disabled) as per instructions given here: https://docs.ava.network/v1.0/en/tutorials/creating-a-local-testnet/ 
2) Create 2 keystore users on distinct nodes(1 user per node, for 2 nodes), using keystore.createUser API (https://docs.ava.network/v1.0/en/api/keystore/#keystorecreateuser)
3) Using avm.importKey API (https://docs.ava.network/v1.0/en/api/avm/#avmimportkey), create an Address with a non-zero AVA balance on one node
4) Using avm.createAddress API (https://docs.ava.network/v1.0/en/api/avm/#avmcreateaddress) , create another Address with a zero AVA balance on a different node.
5) Using avm.send API (https://docs.ava.network/v1.0/en/quickstart/ava-getting-started/#send-ava), send some nAVA to perform a transaction, and the output json result will be a txID.
 6) Using avm.getTxStatus API (https://docs.ava.network/v1.0/en/quickstart/ava-getting-started/#checking-the-transaction-status), check the transaction status. It will show 'Pending'.

**Expected behavior**
The transaction status should've been 'Accepted', if a well-formed transaction has been performed (from non-zero balance to zero balance).

**Additional context**
While repeating the same for a single node network, (in steps 3 and 4, create addresses on the only node, and perform the transaction), the transaction status is 'Accepted'

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@slniko11 Hi, thanks for reporting this. I'm actually seeing this locally, too.
In the mean time, try creating a network with staking **enabled** using the instructions here: https://docs.ava.network/v1.0/en/tutorials/creating-a-local-testnet/

Let me know if this doesn't work, either. 

@aaronbuchwald Have you had a chance to look into this yet?

**Comment by aaronbuchwald** [comment]
Hi @slniko11 thanks for pointing this out, I'm currently looking into this and will have a fix for it ASAP. In the meantime, as Dan said, the script five_node_staking.lua in avash should work for spinning up a local net right now
