### ISSUE TITLE
Feature: print program version as "ava/0.x.y" or "gecko 0.x.y"

### ISSUE THREAD

**Issue by moreati** [ava-labs/gecko#226]
`-version` currently prints `avalanche/0.5.1`. I propose the name should match the name of the binary, e.g `ava/0.5.1`, `ava 0.5.1`. Goal is to reduce confusion for users unfamiliar with Avalanche terminology.

_Originally posted by @moreati in https://github.com/ava-labs/gecko/pull/216_

**Comment by danlaine** [comment]
On 0.6.2, binary name matches version printed.
```
$ ./build/avalanche -version
avalanche/0.6.2 [database=v0.6.1, network=testnet/everest]
```
