### ISSUE TITLE
Error when press Ctrl + C

### ISSUE THREAD

**Issue by Kmortyk** [ava-labs/gecko#232]
**Describe the bug**
Got an error when I pressed Ctrl + C during subnet creation.

**Operating System**
Ubuntu 18.04

[log.txt](https://github.com/ava-labs/gecko/files/4751569/log.txt)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@Kmortyk Thanks for reporting. Looking into this.
What version are you running? You can check with `./ava --version`

**Comment by Kmortyk** [comment]
I am running `avalanche/0.5.4`

**Comment by danlaine** [comment]
And what version of Go?
`go version`

**Comment by Kmortyk** [comment]
Sorry for the lack of context, the go version is `1.13.3 linux / amd64`.

**Comment by danlaine** [comment]
Should be resolved by #236
Let us know if you see this again and we will re-open. Thanks!
