### ISSUE TITLE
platformvm unissuedEvents ordering

### ISSUE THREAD

**Issue by bb-2** [ava-labs/gecko#233]
**Describe the bug**
The IssueTx function in platformvm [modifies the vm.unissuedEvents](https://github.com/ava-labs/gecko/blob/master/vms/platformvm/service.go#L1278) heap independent of the startTime or endTime ordering 

**To Reproduce**
IssueTx's and check the heap order of tx's startTime or endTime values

**Expected behavior**
It should use the EventHeap's Add function or heap.push to add new events.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for catching this @bb-2 ! Fixing this now
