### ISSUE TITLE
Gecko 0.5.5 fatal error: unexpected signal during runtime execution after bootstrapping

### ISSUE THREAD

**Issue by hodadodi** [ava-labs/gecko#239]
Hi, since the update on 0.5.5, I experienced the following problem already thrice. Bootstrapping and everything is fine. I installed the update through git pull in a WSL Ubuntu environment. Below you can find the full log: 

[Gecko 0.5.5.log](https://github.com/ava-labs/gecko/files/4760159/Gecko.0.5.5.log)

**Comment by danlaine** [comment]
This should be resolved by #256 
Try upgrading and if you're still facing this issue, let me know and I will re-open this issue.
