### ISSUE TITLE
ava node crashes on startup (runs out of memory)

### ISSUE THREAD

**Issue by zenpoet** [ava-labs/gecko#240]
**Describe the bug**
On startup, ava daemon runs out of memory. My machine has 3GB of memory, which should have been sufficient? Attached is output from `htop`.

I first had 0.5 running and upgraded ava to 0.5.5

**To Reproduce**
This happened during challenge II, with ava 0.5.5

**Expected behavior**
Not crash

**Screenshots**

**Operating System**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Additional context**
Per @cgcardona's request, attaching various profiles.
For reference my handle on discord is @zenpoet

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

<img width="1182" alt="Screen Shot 2020-06-10 at 3 47 31 PM" src="https://user-images.githubusercontent.com/11259850/84313601-c2055580-ab34-11ea-852c-04902ff772da.png">

[cpu.profile.gz](https://github.com/ava-labs/gecko/files/4760909/cpu.profile.gz)
[lock.profile.gz](https://github.com/ava-labs/gecko/files/4760910/lock.profile.gz)
[mem.profile.gz](https://github.com/ava-labs/gecko/files/4760911/mem.profile.gz)

**Comment by danlaine** [comment]
Hi all, thanks for reporting. We're working on this issue now and a patch should be out in the near future. Thanks for your patience :)

**Comment by tanselkaya** [comment]
Here is my case:
IP Address: 102.130.116.5
CPU Cores: 2
Memory: 4.00 GB
SSD: 100.00 GB

This node is in South Africa. If it helps I can give you root access to the machine if you DM me. I set it up just for the testnet. 
[logs.tar.gz](https://github.com/ava-labs/gecko/files/4779790/logs.tar.gz)

**Comment by danlaine** [comment]
Should be resolved by #256

If you still have this issue after upgrading, please let me know and I will re-open this issue.
