### ISSUE TITLE
[Vulnerability] Possible DDoS attack vector

### ISSUE THREAD

**Issue by Blindripper** [ava-labs/gecko#242]
**Describe the bug**
AVA account creation doesn't cost anything at the moment. X-Chain and P-Chain accounts can be created for free.

This opens a possible DDoS attack vector, where a attacker can spam the network constantly with account creation operations.

Beside that network gets bloated it also takes network performance which could be used more reasonable. In the worst case, if many do this at the same time, the network will stall. 

**To Reproduce**
```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :2,
    "method" :"avm.createAddress",
    "params" :{
        "username":"user",
        "password":"pass"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
```
or

```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.createAccount",
    "params": {
        "username":"user",
        "password":"pass"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```

**Expected behavior**
Set accounts as `inactive` after they are created and `activate` them if they get funded.
A faucet (even for mainnet) would allow for easy on-boarding of developers and prevent bloating the network.

**Operating System**
Any

**Additional context**
This is a realistic Attack, which already happened at Tezos. They introduced a burn fee for newly created accounts after this attack. 

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@Blindripper Accounts live on nodes and there is no transaction associated with account creation, so this isn't really an issue. Thanks for the suggestion, though :)
