### ISSUE TITLE
`avm.importKey` create duplicates

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/gecko#243]
**Describe the bug**
If you perform multiple time the same call to the AVM `importKey`, the address linked to the private key is added each time to the list of address owned by the user.

![image](https://user-images.githubusercontent.com/29312251/84428669-286aa080-ac27-11ea-8edd-3a114a5091e9.png)

**To Reproduce**
Perform multiple times the call to `avm.importKey` wit the same `privateKey` .

**Expected behavior**
Imho it should be the same behaviour as for `platform.importKey` , which does not create duplicates as per my tests 

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for catching this @tbrunain , I'll fix this ASAP
