### ISSUE TITLE
Gecko crash - "Too many open files"

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/gecko#248]
**Describe the bug**
Since yesterday I can't keep my node up for more than few minutes. It crash and I can see "too many open files" in the logs .

**To Reproduce**
I run Gecko 0.5.5 from the source, using nohup .
nohup ./build/ava --log-level=DEBUG --public-ip=xxx.xx.xx.xx &

**Expected behavior**
Well no crash ? :p 

**Screenshots**

**Operating System**

> Linux 5.3.0-59-generic #53-Ubuntu SMP Wed Jun 3 15:52:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

[gecko.logs.zip](https://github.com/ava-labs/gecko/files/4774367/gecko.logs.zip)

Am not doing anything special beside hitting Gecko with some api calls (Admin/Platform/AVM ...) .

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by tbrunain** [comment]
I restarted my server once again and launched Gecko . For now it looks like it's running fine . Will monitor that and give update if crash occurs again .

**Comment by mustafa-kahraman** [comment]
Same here... My node uses too much cpu. My sever has 4 cores and 32gb ram.
CPU usage is min 200% always....

**Comment by danlaine** [comment]
@tbrunain @mustafa-kahraman 
#256 has a lot of performance improvements...if you're still facing these issues, please upgrade and see if that fixes them. Let us know :)
