### ISSUE TITLE
IPC connection failing for local testnet C-Chain

### ISSUE THREAD

**Issue by michaelbnewman** [ava-labs/gecko#254]
**Describe the bug**
ipcs.publishBlockchain called to request IPC connection to blockchainID "C". Both web3py and web3js unable to connect with the provided IPC socket.

**To Reproduce**

source  ~/.gvm/scripts/gvm
gvm use go1.13.12

echo Clean up older versions:
test -d ~/.gecko && rm -f -r ~/.gecko
test -d $GOPATH/src/github.com/ava-labs && rm -f -r $GOPATH/src/github.com/ava-labs

echo build gecko
go get -d -v github.com/ava-labs/gecko/...
cd $GOPATH/src/github.com/ava-labs/gecko
./scripts/build.sh
./build/ava --version  # avalanche/0.5.5 [database=v0.5.0, network=testnet/denali]

echo build avash
cd $GOPATH
go get github.com/ava-labs/avash
cd src/github.com/ava-labs/avash
go build

echo run avash
cd $GOPATH/src/github.com/ava-labs/avash
./avash
runscript scripts/five_node_staking.lua
procmanager list  # shows that "--api-ipcs-enabled=true" is correctly set

curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "ipcs.publishBlockchain",
    "params":{
        "blockchainID":"C"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/ipcs

_{"jsonrpc":"2.0","result":{"url":"ipc:///tmp/tZGm6RCkeGpVETUTp11DW3UYFZmm69zfqxchpHrSF7wgy8rmw.ipc"},"id":1}_

web3py RPC returns the current blockNumber:

`from web3 import Web3`
`provider = Web3.HTTPProvider("http://127.0.0.1:9650/ext/C/rpc")`
`w3 = Web3(provider)`
`print(w3.eth.blockNumber)`

web3py IPC test fails:

`from web3 import Web3`
`provider = Web3.IPCProvider("/tmp/tZGm6RCkeGpVETUTp11DW3UYFZmm69zfqxchpHrSF7wgy8rmw.ipc")`
`w3 = Web3(provider)`
`print(w3.eth.blockNumber)`

web3py IPC result: `ConnectionResetError: [Errno 104] Connection reset by peer`

web3js RPC works:

`const Web3 = require('web3')`
`const rpcURL = "http://127.0.0.1:9650/ext/C/rpc"`
`const web3 = new Web3(rpcURL)`
`web3.eth.getBlockNumber().then(console.log)`

web3js IPC test fails:

`const Web3 = require('web3')`
`var net = require('net');`
`var web3 = new Web3('/tmp/tZGm6RCkeGpVETUTp11DW3UYFZmm69zfqxchpHrSF7wgy8rmw.ipc', net);`
`web3.eth.getBlockNumber().then(console.log)`

web3js IPC Response:  ``Error: Invalid JSON RPC response: "\u0000SP\u0000\u0000 \u0000\u0000"``

**Expected behavior**
RPC and IPC should work interchangeably. 

**Operating System**
Using Ubuntu 18.04.4

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Hi @michaelbnewman , the gecko IPC is actually not implementing the same interface as the RPC endpoint. After publish blockchain is called, gecko will publish recent consensus decisions to that endpoint so that services like the explorer can listen to it.

**Comment by michaelbnewman** [comment]
Thanks @aaronbuchwald , so this is not a bug. I suppose this issue could be changed from a bug report to a feature request to have an IPC connection compatible with the data provided by RPC and WS for C-Chain (unclear to me if this is more of a plugin issue that would go with coreth instead?). Otherwise, this can be a closed issue for now.

**Comment by danlaine** [comment]
Going to close this; would welcome the opening of a feature request issue for this

**Comment by arthurwolf** [comment]
The documentation should at least explain the IPC feature is different from the 3 other chain software I've worked with, and can't be used with a web3/ethers IPCProvider... Would have saved me 45 minutes ...
