### ISSUE TITLE
release 0.5.7 faucet still not working, fundes not received

### ISSUE THREAD

**Issue by nlpvan-paul** [ava-labs/gecko#267]
**Describe the bug**
test funds sent from faucet are not received on x chain address

**To Reproduce**
check funds on address - X-7263Hsukb3Wk8KP42Wd75dCh6XV7mAuFY
send test ava from faucet - https://faucet.avax.network/
to same address - X-7263Hsukb3Wk8KP42Wd75dCh6XV7mAuFY
check balances - currently 0 / zero

to check funds / get balances, when having a running node do -
curl -X POST --data '{ "jsonrpc":"2.0", "id"     :3, "method" :"avm.getBalance", "params" :{ "address":"X-7263Hsukb3Wk8KP42Wd75dCh6XV7mAuFY", "assetID"  :"AVA" } }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X

**Expected behavior**
balances increasing after every sending from faucet

**Screenshots**
n.a.

**Operating System**
ubuntu 18.04 / 20.04

**Additional context**
node running 0.5.7

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Hi, sorry to hear you're still having issues.
Is your node finished bootstrapping the X-Chain? Did it print a log like this?
`INFO [06-29|18:06:29] <X Chain> /snow/engine/avalanche/transitive.go#84: bootstrapping finished with 1 vertices in the accepted frontier`

**Comment by nlpvan-paul** [comment]
as a test for bootstrapping I do -
$ curl -X POST --data '{ "jsonrpc":"2.0", "id"     :3, "method" :"avm.getBalance", "params" :{ "address":"X-6cesTteH62Y5mLoDBUASaBvCXuL2AthL", "assetID"  :"AVA" } }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
    and I get -
{"jsonrpc":"2.0","result":{"balance":"45000000000000000","utxoIDs":[{"txID":"21d7KVtPrubc5fHr6CGNcgbUb4seUjmZKr35ZX7BZb5iP8pXWA","outputIndex":1}]},"id":3}

is the node bootstrapped or  not?

    On Monday, June 29, 2020, 3:06:59 PM PDT, danlaine <notifications@github.com> wrote:  
 
 


Hi, sorry to hear you're still having issues.
Is your node finished bootstrapping the X-Chain? Did it print a log like this?
INFO [06-29|18:06:29] <X Chain> /snow/engine/avalanche/transitive.go#84: bootstrapping finished with 1 vertices in the accepted frontier

**Comment by danlaine** [comment]
No, it does not look like your node is bootstrapped if you're getting that response. Is your node unable to bootstrap?

**Comment by nlpvan-paul** [comment]
I assume the node is already bootstrapped if the balance of a pre-funded address is not 0 but 45000000000000000.
I am willing to remove folders in order to start fresh.which folders do I remove?

how is the node started -- ./ava (no parameters)- or, ./ava + parameters
    On Tuesday, June 30, 2020, 5:44:58 AM PDT, danlaine <notifications@github.com> wrote:  
 
 


No, it does not look like your node is bootstrapped if you're getting that response. Is your node unable to bootstrap?

**Comment by danlaine** [comment]
Going to close this issue since it seems like a local issue. Please message us on Discord if you still need help.
