### ISSUE TITLE
0.5.7 node - faucet not working even for genesis pre-funded addresses

### ISSUE THREAD

**Issue by nlpvan-paul** [ava-labs/gecko#268]
**Describe the bug**
this is a follow up of the faucet not working bug - funds sent by faucet are  not received on addresses

**To Reproduce**
ava has a number of pre-funded addresses, here are 3 of them -
		FundedAddresses: []string{
			"9uKvvA7E35QCwLvAaohXTCfFejbf3Rv17",
			...
			"ZdhZv6oZrmXLyFDy6ovXAu6VxmbTsT2h",
			"6cesTteH62Y5mLoDBUASaBvCXuL2AthL",

to  reproduce send funds to all 3 addresses and check if the balance does change

$ curl -X POST --data '{ "jsonrpc":"2.0", "id"     :3, "method" :"avm.getBalance", "params" :{ "address":"X-9uKvvA7E35QCwLvAaohXTCfFejbf3Rv17", "assetID"  :"AVA" } }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
      result -
{"jsonrpc":"2.0","result":{"balance":"45000000000000000","utxoIDs":[{"txID":"21d7KVtPrubc5fHr6CGNcgbUb4seUjmZKr35ZX7BZb5iP8pXWA","outputIndex":7}]},"id":3}

$ curl -X POST --data '{ "jsonrpc":"2.0", "id"     :3, "method" :"avm.getBalance", "params" :{ "address":"X-ZdhZv6oZrmXLyFDy6ovXAu6VxmbTsT2h", "assetID"  :"AVA" } }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
     result -
{"jsonrpc":"2.0","result":{"balance":"45000000000000000","utxoIDs":[{"txID":"21d7KVtPrubc5fHr6CGNcgbUb4seUjmZKr35ZX7BZb5iP8pXWA","outputIndex":2}]},"id":3}

$ curl -X POST --data '{ "jsonrpc":"2.0", "id"     :3, "method" :"avm.getBalance", "params" :{ "address":"X-6cesTteH62Y5mLoDBUASaBvCXuL2AthL", "assetID"  :"AVA" } }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
      result -
{"jsonrpc":"2.0","result":{"balance":"45000000000000000","utxoIDs":[{"txID":"21d7KVtPrubc5fHr6CGNcgbUb4seUjmZKr35ZX7BZb5iP8pXWA","outputIndex":1}]},"id":3}

**Expected behavior**
balances have to change on all 3 addresses

**Screenshots**
n.a

**Operating System**
ubuntu 18.04 / 20.04

**Additional context**
this is important to be fixed because a Dapp developer can not use most of the api - no gas!

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Hi @nlpvan-paul I don't think I understand. Are you sending faucet drips to these addresses and they're not appearing?

**Comment by nlpvan-paul** [comment]
yes - sending 20k nAVA from faucet to 3 of the genesis pre-funded  addresses

    On Tuesday, June 30, 2020, 8:20:27 AM PDT, danlaine <notifications@github.com> wrote:  
 
 


Hi @nlpvan-paul I don't think I understand. Are you sending faucet drips to these addresses and they're not appearing?

**Comment by danlaine** [comment]
Going to close this issue since it seems like a local issue. Please message us on Discord if you still need help.
