### ISSUE TITLE
errTimestampTooEarly = errors.New("block's timestamp is later than its parent's timestamp")

### ISSUE THREAD

**Issue by zefonseca** [ava-labs/gecko#271]
**Describe the bug**
Incorrect error message.

**To Reproduce**

Static error.

Line 14 of vms/timestampvm/block.go

    	errTimestampTooEarly = errors.New("block's timestamp is **later** than its parent's timestamp")

**Expected behavior**

Should read : 
    	errTimestampTooEarly = errors.New("block's timestamp is **earlier** than its parent's timestamp")

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for catching this @zefonseca , just made a PR to fix the error message
