### ISSUE TITLE
Version problem with nanomsg's mangos

### ISSUE THREAD

**Issue by samettonyali** [ava-labs/gecko#280]
**Describe the bug**
This is not a bug actually, rather, an update request.

**To Reproduce**
You can try to install ava on raspberry pi OS.

**Expected behavior**
A brand new node on ava test network.

**Operating System**
Raspberry pi OS

**Additional context**
I tried to install ava on my raspberry pi 4, but it failed at dependency installation part. First, I though it is an architecture problem and was about to give up, then I realized it is about version of mangos that is used in go.mod file: nanomsg.org/go/mangos/v2 v2.0.8. However, I found this caveat at [mangos's github page](https://github.com/nanomsg/mangos): "The import path has changed! Please change any references from nanomsg.org/go/mangos/v2 to go.nanomsg.org/mangos/v3. The old v2 imports will still work for old applications, provided that a sufficiently modern version of Go is used. However, no further work will be done on v2." So, I believe go.mod file and maybe some other parts must be updated in compliance with mangos v3.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for reporting this! Just opened a PR to update the mangos dependency
