### ISSUE TITLE
Windows build can't find "sh" while creating chain

### ISSUE THREAD

**Issue by ssg** [ava-labs/gecko#283]
**Describe the bug**
Ava.exe shows the error that the command "sh" isn't found as it doesn't exist on Windows.

**To Reproduce**
Start ava.exe
Observe this message:

```
INFO [07-11|14:52:24] /chains/manager.go#187: creating chain:
... redacted ...
ERROR[07-11|14:52:24] /chains/manager.go#242: error while creating vm: exec: "sh": executable file not found in %PATH%
```

**Expected behavior**
No errors should be shown.

**Screenshots**
N/A

**Operating System**
Windows 10 64-bit w/ May 2020 Update

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
@ssg Should be resolved by https://github.com/ava-labs/gecko/commit/5d67d92705a0cdc235ea9ec21c8deb8cc183fcd6
Let us know if you have this issue again.

**Comment by ssg** [comment]
Thank you!
