### ISSUE TITLE
Spdag OutputTakeOrLeave timelocks

### ISSUE THREAD

**Issue by bb-2** [ava-labs/gecko#284]
**Describe the bug**
The OutputTakeOrLeave [locktime2](https://github.com/ava-labs/gecko/blob/master/vms/spdagvm/output.go#L191) blocks the Unlock function independent of locktime1 and addresses1. 

**Expected behavior**
Unlocking for otol.addresses1 and otol.addresses2 seems like they should be independent based on [comments](https://github.com/ava-labs/gecko/blob/master/vms/spdagvm/output.go#L139) and [test example](https://github.com/ava-labs/gecko/blob/master/vms/spdagvm/output_test.go#L83)

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
We're going to remove spdag and spchain so I'm gonna close this
