### ISSUE TITLE
Adding a validator to a non-default subnet with min 2 control keys does not seem to function

### ISSUE THREAD

**Issue by arikan** [ava-labs/gecko#286]
**Describe the bug**

Adding a validator to a non-default subnet with min 2 control keys does not seem to function. Currently on the Denali testnet, there is no subnet that has 2 control keys and validators added.

**To Reproduce**

Get Node ID
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "info.getNodeID",
    "params":{},
    "id": 84
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/info
```
> {"jsonrpc":"2.0","result":{"nodeID":"DdXmzo1uy5ZkB231uZofakuSvWSpVr5CS"},"id":84}

The node ID must be in the Default Subnet validators:
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getCurrentValidators",
    "params": {},
    "id": 5
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
```
,
{
    "startTime": "1594651806",
    "endTime": "1626187206",
    "stakeAmount": "10000",
    "address": "PEqt16m7mbJTFxbqvTv5XqLEJ1cFkSfY6",
    "id": "DdXmzo1uy5ZkB231uZofakuSvWSpVr5CS"
},
```

The Non-Default Subnet is created with two control keys and listed in `platform.getSubnets`
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getSubnets",
    "params": {},
    "id": 6
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```

```
,
{
    "id": "2e6f4bHwr7F7Ejz24WuYqdfPRsXAKzetcgVTG1esfe1cgpHgZZ",
    "controlKeys": [
        "6J9jP8ewtXPEgKjqpACVdrPTceocf6JHB",
        "M5VBh7hKtCrpq4yuWyY7Lb4uJckxkkxh8"
    ],
    "threshold": "2"
},
```

Get the current nonce
```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"platform.getAccount",
    "params" :{
        "address": "PEqt16m7mbJTFxbqvTv5XqLEJ1cFkSfY6"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
> {"jsonrpc":"2.0","result":{"address":"PEqt16m7mbJTFxbqvTv5XqLEJ1cFkSfY6","nonce":"5","balance":"25002"},"id":1}

Create the Unsigned Transaction (iterating the current nonce)
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.addNonDefaultSubnetValidator",
    "params": {
        "id":"DdXmzo1uy5ZkB231uZofakuSvWSpVr5CS",
        "subnetID":"2e6f4bHwr7F7Ejz24WuYqdfPRsXAKzetcgVTG1esfe1cgpHgZZ",
        "startTime":'$(date --date="10 minutes" +%s)',
        "endTime":'$(date --date="365 days" +%s)',
        "weight":1,
        "payerNonce":6
    },
    "id": 5
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
> {"jsonrpc":"2.0","result":{"unsignedTx":"111927emgbpbwDd2fV6AERSXEJgQkF3ej1X6fSjtq3bKY6qPFdcEe3YnKMY8yNcwFSDxsibCHRiXStfwmSGCKwz2bW32gVJhBqGsHWTXBXa7HLqf9MgjWWDWSoUJ7hVeKbWgTqhu4Zzi7U6MoXL8S1VBF6zwj6xtMyH9UgoiJg8FsW5nxFhUyrbVEznJswjBaYAhEp1MCbuWRSRpmNadP3AV7rxbjaAi"},"id":5}

Sign this transaction with one of the Subnet control keys
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.sign",
    "params": {
        "tx":"111927emgbpbwDd2fV6AERSXEJgQkF3ej1X6fSjtq3bKY6qPFdcEe3YnKMY8yNcwFSDxsibCHRiXStfwmSGCKwz2bW32gVJhBqGsHWTXBXa7HLqf9MgjWWDWSoUJ7hVeKbWgTqhu4Zzi7U6MoXL8S1VBF6zwj6xtMyH9UgoiJg8FsW5nxFhUyrbVEznJswjBaYAhEp1MCbuWRSRpmNadP3AV7rxbjaAi",
        "signer":"6J9jP8ewtXPEgKjqpACVdrPTceocf6JHB",
        "username":"FIRST CONTROL ACCOUNT USERNAME",
        "password":"FIRST CONTROL ACCOUNT PASSWORD"
    },
    "id": 6
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
> {"jsonrpc":"2.0","result":{"tx":"11148ANvWAKVn9cEFSidfACx9ysyVK9hvTBbiCKFL3th8aqRDSciBy2LM9rir4kNHQszTnYxF1c2tZk6BQtQw1DWE9cW9pWPQVYcvZdSHdvRQi3pdUNfXbdHJb5YT2qSANRrH5vMAopajuuyECZeWsdU4FwtBpdSVVMCKWKPHeX5sF8s6E5Ur9n3WSjpMB2Ln5pEHm4SjPGg3vFzgmDAuR2QB2RbfaWK9Bi5wapzdQTZ7NuF8pWtxMi1btYAjXam3NvFzcBfjvuisqensGUpJZr13J1tNbJ84RAuFxb9P54NgzSKzc73e7xG1"},"id":6}

Sign this partially singed transaction with the other control key of the Subnet
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.sign",
    "params": {
        "tx":"11148ANvWAKVn9cEFSidfACx9ysyVK9hvTBbiCKFL3th8aqRDSciBy2LM9rir4kNHQszTnYxF1c2tZk6BQtQw1DWE9cW9pWPQVYcvZdSHdvRQi3pdUNfXbdHJb5YT2qSANRrH5vMAopajuuyECZeWsdU4FwtBpdSVVMCKWKPHeX5sF8s6E5Ur9n3WSjpMB2Ln5pEHm4SjPGg3vFzgmDAuR2QB2RbfaWK9Bi5wapzdQTZ7NuF8pWtxMi1btYAjXam3NvFzcBfjvuisqensGUpJZr13J1tNbJ84RAuFxb9P54NgzSKzc73e7xG1",
        "signer":"M5VBh7hKtCrpq4yuWyY7Lb4uJckxkkxh8",
        "username":"SECOND CONTROL ACCOUNT USERNAME",
        "password":"SECOND CONTROL ACCOUNT PASSWORD"
    },
    "id": 7
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
> {"jsonrpc":"2.0","result":{"tx":"1112DZcYwFuwv1DoQz8nyvqCPJFocuZNpUqncQyhoKbHwgx2iiBcuV6oasPbeWxU3Rh6z4zuapLKLDRtezbympbH8UWFgNJLGqxKV21teAWwto8iTAanKZ4pGASbVbVWvaCMjN8craeoAzprCDmZdp6KNYBNcmRsxUKJwKGZvr6y73XXgQnGhw3RN26ZkAHPL2rxUAVW7BEbhXh3ox8vdafWVWoEGHRVMCYcBudJeePUfJy6y8TTzNENMdjK6CbD4B2ude36heAarWG3G6RtBYWTbbm9xUxFAUXb744nNndqdWR1NqpHR36ep1dhTxAhxXVbgCAJTbSryPPRcsEC7nkEaEzLa3XQHhkwWSweVMiFoJHrNE771QVzj1y1Kkj8yfRqRWqJSNnxLi98LS"},"id":7}

Sign this partial transactio with the account that will pay the transaction fee
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.sign",
    "params": {
        "tx":"1112DZcYwFuwv1DoQz8nyvqCPJFocuZNpUqncQyhoKbHwgx2iiBcuV6oasPbeWxU3Rh6z4zuapLKLDRtezbympbH8UWFgNJLGqxKV21teAWwto8iTAanKZ4pGASbVbVWvaCMjN8craeoAzprCDmZdp6KNYBNcmRsxUKJwKGZvr6y73XXgQnGhw3RN26ZkAHPL2rxUAVW7BEbhXh3ox8vdafWVWoEGHRVMCYcBudJeePUfJy6y8TTzNENMdjK6CbD4B2ude36heAarWG3G6RtBYWTbbm9xUxFAUXb744nNndqdWR1NqpHR36ep1dhTxAhxXVbgCAJTbSryPPRcsEC7nkEaEzLa3XQHhkwWSweVMiFoJHrNE771QVzj1y1Kkj8yfRqRWqJSNnxLi98LS",
        "signer":"PEqt16m7mbJTFxbqvTv5XqLEJ1cFkSfY6",
        "username":"PAYING ACCOUNT USERNAME",
        "password":"PAYING ACCOUNT PASSWORD"
    },
    "id": 8
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
> {"jsonrpc":"2.0","result":{"tx":"1112DZcYwFuwv1DoQz8nyvqCPJFocuZNpUqncQyhoKbHwgx2iiBcuV6oasPbeWxU3Rh6z4zuapLKLDRtezbympbH8UWFgNJLGqxKV21teAWwto8iTAanKZ4pGASbVbVWvaCMjN8craeoAzprCDmZdp6KNYBNcmRsxUKJwKGZvr6y73XXgQnGhw3RN26ZkAHPL2rxUAVW7BEbhXh3ox8vdafWVWoEGHRVMCYcBudJeePUfJy6y8TTzNENMdjK6CbD4B2ude36heAarWG3G6RtBYWTbbm9xUxFAUXb744nNndqdWR1NqpKWa5aJHmr2v27sSig6bmDaNZp74RNRD9WA89E1hrKij2TjEJfigi1NDHcuwoZFDdAkbuamruVAzFNvLgviqP2C4K2MLwCkn"},"id":8}

Issue the transaction
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.issueTx",
    "params": {
        "tx":"1112DZcYwFuwv1DoQz8nyvqCPJFocuZNpUqncQyhoKbHwgx2iiBcuV6oasPbeWxU3Rh6z4zuapLKLDRtezbympbH8UWFgNJLGqxKV21teAWwto8iTAanKZ4pGASbVbVWvaCMjN8craeoAzprCDmZdp6KNYBNcmRsxUKJwKGZvr6y73XXgQnGhw3RN26ZkAHPL2rxUAVW7BEbhXh3ox8vdafWVWoEGHRVMCYcBudJeePUfJy6y8TTzNENMdjK6CbD4B2ude36heAarWG3G6RtBYWTbbm9xUxFAUXb744nNndqdWR1NqpKWa5aJHmr2v27sSig6bmDaNZp74RNRD9WA89E1hrKij2TjEJfigi1NDHcuwoZFDdAkbuamruVAzFNvLgviqP2C4K2MLwCkn"
    },
    "id": 9
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
{"jsonrpc":"2.0","result":{"txID":"f233BsEesJt1D6cs986APtuAenkY4YNnhavjEtifdSNGmZUdK"},"id":9}

Verify (within 10 mins after creating the Unsigned Transaction above)
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "platform.getPendingValidators",
    "params": {
        "subnetID":"2e6f4bHwr7F7Ejz24WuYqdfPRsXAKzetcgVTG1esfe1cgpHgZZ"
    },
    "id": 10
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/P
```
> {"jsonrpc":"2.0","result":{"validators":[]},"id":10}

**Expected behavior**
1. `platform.getPendingValidators` should NOT return an empty list of pending validators. 
2. 10 minutes after creating the Unsigned Transaction, the node ID should show up in non-default subnet validators list.

**Operating System**
Ubuntu 18.04.4

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Hmm it seems that you're following all the right steps. Not sure why the tx doesn't get accepted.

What's likely happening is that the tx is getting silently rejected but there's no way to check at the moment other than to run with `--log-level=debug` and look for an error message. Can you try following this flow again with that debug level and seeing what it prints when the tx is issued?

**Comment by danlaine** [comment]
@arikan Do you still have this issue with the latest release?

**Comment by arikan** [comment]
Hi @danlaine, as of Everest, I was able to run a non-default subnet with min 2 control keys. Thanks.
