### ISSUE TITLE
Jsonrpc method avm.getBalance returning checksum error

### ISSUE THREAD

**Issue by fkbenjamin** [ava-labs/gecko#300]
I have synced a fresh node using the v0.5.7 release tag on an Ubuntu 18.04 VM. Following the [Getting Started Page](https://docs.avax.network/v1.0/en/quickstart/ava-getting-started/), I have created a new user, created an address on X-Chain and requested some funds from the faucet (tx was visible as successful on the testnet explorer). 

Now, trying to query the balance of the account via the RPC as described in the Getting Started page, I executed the following:

```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :3,
    "method" :"avm.getBalance",
    "params" :{
        "address":"X-GTcks3DzK6fCQusj1hXREwkRLyCmU65T1",
        "assetID"  :"AVAX"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
```

That returned the following error:

```
{"jsonrpc":"2.0","error":{"code":-32000,"message":"input string is smaller than the checksum size","data":null},"id":3}
```

I was considering if I maybe copy/pasted an incorrect address, but trying it with the exact example listed in the docs, it returns the same error. So I assume it's not a typo.

```
curl -X POST --data '{
>     "jsonrpc":"2.0",
>     "id"     :3,
>     "method" :"avm.getBalance",
>     "params" :{
>         "address":"X-5TQr5hSAZ8ZKuSaYLg5sr4VwvcvwKZ1Mg",
>         "assetID"  :"AVAX"
>     }
> }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
{"jsonrpc":"2.0","error":{"code":-32000,"message":"input string is smaller than the checksum size","data":null},"id":3}
```

I assume my node is synced correctly by looking at the logs and seeing this:

```
INFO [07-21|03:10:31] <X Chain> /snow/engine/avalanche/transitive.go#84: bootstrapping finished with 1 vertices in the accepted frontier
```

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by fkbenjamin** [comment]
Minor Update: I believe that the exception for the asset-id "AVAX" is not working.

Querying other asset-ids seems to work just fine:

```
curl -X POST --data '{
  "jsonrpc":"2.0",
  "id"     : 1,
  "method" :"avm.getBalance",
  "params" :{
      "address":"X-GTcks3DzK6fCQusj1hXREwkRLyCmU65T1",
      "assetID": "2pYGetDWyKdHxpFxh2LHeoLNCH6H5vxxCxHQtFnnFaYxLsqtHC"
  }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
```
returns this valid result:
```
{"jsonrpc":"2.0","result":{"balance":"0","utxoIDs":[]},"id":1}
```

**Comment by danlaine** [comment]
@fkbenjamin Thanks for reporting. This has been fixed; the documentation and code now both use `AVAX`, not `AVA`.
