### ISSUE TITLE
Feature request: Memo in avm.send

### ISSUE THREAD

**Issue by slideloft** [ava-labs/gecko#321]
Currently if a user is sending avax or any other token to another wallet address it works in the following.
```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :5,
    "method" :"avm.send",
    "params" :{
        "username"   :"YOUR USERNAME HERE",
        "password"   :"YOUR PASSWORD HERE",
        "assetID"    :"AVAX",
        "amount"     :1000,
        "to"         :"X-avax1w4nt49gyv4e99ldqevy50l2kz55y9efghep0cs"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
```

What is a memo?
A memo is a message included with a transaction.
This feature would allow users communicate with each other, it also helps serves as a note or reminder for a transaction, it can also be utilize by apps in sorting payments or looking up transactions.

How it would work on gecko

```
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :5,
    "method" :"avm.send",
    "params" :{
        "username"   :"YOUR USERNAME HERE",
        "password"   :"YOUR PASSWORD HERE",
        "assetID"    :"AVAX",
        "amount"     :1000,
        "memo"       :bought coffee,
        "to"         :"X-avax1w4nt49gyv4e99ldqevy50l2kz55y9efghep0cs"
    }
}' -H 'content-type:application/json;' 
```
I would also propose two memo types which includes : 

- Text (for including a message of up to 28 bytes with your transaction)
- Memo ID (for the receiving party to be able to identify the sending party)
In my example i used a `Text` based memo type, if i used `Memo ID`  then it could be `"memo"       :00123456,` the `00123456` could be an account number the receiver of the above tx should make payment to.

Well Avalanche is the internet of finance.

**Comment by danlaine** [comment]
done https://github.com/ava-labs/gecko/commit/ab782ba103877ee874bd661b3d551dfa88b6988d
