### ISSUE TITLE
version 0.6.4 for linux doesn't start the node

### ISSUE THREAD

**Issue by AlexDCryptoC** [ava-labs/gecko#325]
![WhatsApp Image 2020-08-25 at 13 32 12](https://user-images.githubusercontent.com/18679675/91165389-36ce4180-e6d9-11ea-8be7-3a86f3d2dabb.jpeg)

I downloaded the avalanche-linux-0.6.4.tar package, but seems this version doesn't start the node after you 'unzip' and run ./avalanche (please check the above screenshot)

Afterwards i downloaded a previous version, avalanche-linux-0.6.2.tar.gz and i managed to start the node from the first try

**Comment by danlaine** [comment]
Can you do `ls -l` in this directory? I assume for some reason the unzip didn't work properly and the binary is empty. I just tried locally and it worked for me.

**Comment by AlexDCryptoC** [comment]
Yap, there was an issue with the unzip. At the end i managed to run the node. Thanks!
