### ISSUE TITLE
avm.buildGenesis throws "string not all lowercase or all uppercase" error

### ISSUE THREAD

**Issue by arikan** [ava-labs/gecko#367]
**Describe the bug**
Calling `avm.buildGenesis` to crerate a fixedCap blockchain throws a "string not all lowercase or all uppercase" error.

**To Reproduce**
```
curl -X POST --data '{
    "jsonrpc": "2.0",
    "id"     : 1,
    "method" : "avm.buildGenesis",
    "params" : {
        "genesisData": {
            "asset1": {
                "name": "My Asset 1",
                "symbol":"AVAZ",
                "initialState": {
                    "fixedCap" : [
                        {
                            "amount":11000000,
                            "address": "X-everest1a9a37muvdsghl85ek5c7dyh02e267au0h8zsev"
                        },
                        {
                            "amount":10000000,
                            "address": "X-everest18eel3fydypflw67l93nc4euphmkdtdpgvyp7q8"
                        }
                    ]
                }
            }
        }
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/vm/avm
```
Returns:
```
{"jsonrpc":"2.0","error":{"code":-32000,"message":"string not all lowercase or all uppercase","data":null},"id":1}
```

**Expected behavior**
This should return the byte representation of the blockchain’s genesis state:
```
{
    "jsonrpc": "2.0",
    "result": {
        "bytes": "111TNWzUtHKoSvxohjyfE..."
    },
    "id": 1
}
```

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for reporting this @arikan , this is definitely not the most helpful error message, so I'm going to create a PR to improve the output.

It looks like the source of this issue is that buildGenesis requires that the addresses passed in do not contain the typical X- prefix used for addresses on the X chain, since it is meant to create an entirely new chain. As in the example call here: https://docs.avax.network/v1.0/en/api/avm/#example-call
you need to remove the X- prefix and then it should return genesis bytes as expected.

**Comment by arikan** [comment]
Thanks @aaronbuchwald, it works. 
https://explorer.avax.network/blockchain/QcNEwnQ8nLDdzstcm1gaQ5FaRybax943BFy2aS45yr8xyYFpX

Well this address format requirement without "X-" should be clearly mentioned in the docs.

**Comment by aaronbuchwald** [comment]
Good point, I just added a PR to explain that chain prefixes should not be included in this call: https://github.com/ava-labs/avalanche-docs/pull/151

**Comment by StephenButtolph** [comment]
I'm closing this as it seems that both the error message has been clarified and the docs have been updated.
