### ISSUE TITLE
Feature request: clearify "bootstrapping finished" definition

### ISSUE THREAD

**Issue by otherpaco** [ava-labs/gecko#370]
When this entry appears in the logs

```sh
bootstrapping finished fetching $int blocks. executing state transitions...
```

a call to `info.isBootstrapped` or `health.getLiveness` will still return `false` or `Chain not bootstrapped`.

This calls will return `true` after all state transitions are executed.

I think the state "bootstrapped" should be defined identically in the logs and in the calls.
Or you should return something like "Chain bootstrapped, executing state transitions" in the Liveness call.

The state transitions can take some time and a User may be confused to see "bootstrapping finished" in the logs and at the same time a different result from the API calls. It reads "bootstrapping finished" in the logs but you are not able to use your node fully at this point.

**Comment by danlaine** [comment]
@otherpaco What would you suggest to make it more clear for users?

**Comment by otherpaco** [comment]
@danlaine depending on the teams definition of "bootstrapped"

**node is bootstrapped when all blocks are fetched:**

After all blocks are fetched before all transitions are executed
- `info.isBootstrapped` should return true  
- `health.getLiveness` shouldn't return any message like "Chain not bootstrapped"
- log stays as is

**node is bootstrapped when all blocks are fetched and all transitions are executed:**
-  `info.isBootstrapped` stays as is
-  `health.getLiveness` stays as is
-  the log entry after fetching all blocks shouldn't say "bootstrapping finished" at this point but after all transitions are executed

Both solutions are consistent.  
I would prefer the latter, because after all transitions are executed one has a node in a ready state to send, receive and so on.

**Comment by StephenButtolph** [comment]
I think the definition of when bootstrapping is finished is currently consistent. But that the wording in the log should be improved to make this especially clear.

The intention of this log was to imply that `bootstrapping had (finished fetching %d blocks)`. Not that `(bootstrapping had finished) [after] fetching %d blocks`

I think a simple clarification to this log would be to change:
```
bootstrapping finished fetching %d blocks. executing state transitions...
```
to:
```
bootstrapping fetched %d blocks. executing state transitions...
```

Bootstrapping is finished once the log `bootstrapping finished with %s as the last accepted block` is displayed.

**Comment by StephenButtolph** [comment]
Handled in #386. Will be included in the next release.

**Comment by otherpaco** [comment]
"bootstrapping fetched $int blocks. executing state transitions..."

Thank you very much
