### ISSUE TITLE
AVM API - avm.listAssets method not found

### ISSUE THREAD

**Issue by giuseppefrancaviglia** [ava-labs/gecko#63]
**Describe the bug**
I'm implementing some examples using slopes, and to query all the assets and their balance for a wallet, I called the method avm.listAssets to query all the assets for the address, but it didn't work. 
I refer to this method: https://docs.ava.network/v1.0/en/tools/slopes/api/classes/_apis_avm_api_.avmapi/#listassets
Following the stacktrace of the error, I checked also the file api.ts, and the listAssets method is defined there (row 411). 

**To Reproduce**
Just calling the method, below my code:
let assets = await avm.listAssets("X-M2rjv2xrpKShRbNA8nXnHi7qgFgZiTCyN")

**Expected behavior**
I expected to get as result the list of Assets (with a positive balance) for the address passed as parameter in the function

**Screenshots**

<img width="746" alt="bug-scr1" src="https://user-images.githubusercontent.com/58706740/79030518-a532bd00-7b99-11ea-83d8-9e37d2fdb5e6.png">

<img width="819" alt="bug-scr2" src="https://user-images.githubusercontent.com/58706740/79030534-b8de2380-7b99-11ea-8699-4bbde96d7c84.png">

<img width="792" alt="api ts" src="https://user-images.githubusercontent.com/58706740/79030539-bed40480-7b99-11ea-9111-ce95c9931046.png">

**Operating System**
OSX 10.13.6

**Additional context**
Talked about this bug on Discord today, @collincusce got it.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by collincusce** [comment]
@danlaine is there a status update here?

**Comment by danlaine** [comment]
`getAllBalances` still hasn't been merged into Gecko...Stephen reviewed yesterday and I'm going to make the changes he requested so hopefully later today it will be in

**Comment by el33th4x0r** [comment]
Let's not forget to add documentation for getAllBalances as well.

**Comment by danlaine** [comment]
`getAllBalances` (new name for `listAssets`) is documented here: https://docs.ava.network/v1.0/en/tools/slopes/api/classes/_apis_avm_api_.avmapi/#getallbalances
