### ISSUE TITLE
lgtm.com warning: err returned by service.vm.getChains() ignored

### ISSUE THREAD

**Issue by moreati** [ava-labs/gecko#78]
**Describe the bug**
In `platformvm.Service.chainExists()` the `err` return value of `service.vm.getChains()` is not checked or propagated. This may indicate unintentional masking of an error. The line in question is

https://github.com/ava-labs/gecko/blob/eacdf54efc2b9bdf8f12bb33d668d0108e8e1651/vms/platformvm/service.go#L1229

This was identified by a static analysis on https://lgtm.com

**To Reproduce**
The complete analysis is viewable at https://lgtm.com/projects/g/ava-labs/gecko/alerts/?mode=list

**Expected behavior**
This return value might be ignored intentional, if so it should be assigned to `_` instead.

**Operating System**
N/A

**Additional context**
lgtm.com is a hosted service that performed static analysis of a code base, looking for common problems. Like any static analysis it can produce false positives. Two further warnings were raised in `spdagvm.Tx.verifyFunds()`, but they look to me like code that could be simplified, rather than bugs. The lines are

https://github.com/ava-labs/gecko/blob/eacdf54efc2b9bdf8f12bb33d668d0108e8e1651/vms/spdagvm/tx.go#L162

https://github.com/ava-labs/gecko/blob/eacdf54efc2b9bdf8f12bb33d668d0108e8e1651/vms/spdagvm/tx.go#L177

I think the functions could be simplifed, to eliminate the warning.

I'd be happy to provide a pull request for all three.

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by moreati** [comment]
I came across these while investigating lgtm.com as a potential way to identify missing calls to `vm.Shutdown()`. It can be integrated as a check on all pull requests, if you're interested.

**Comment by danlaine** [comment]
Resolved by #103
