### ISSUE TITLE
Suggestion: Build successful message while using scripts.sh

### ISSUE THREAD

**Issue by aanupam23** [ava-labs/gecko#96]
*Suggestion: Build successful message while using scripts.sh*

OS: Ubuntu 18.04

*Explanation*
Successful completion of the command `./scripts/build.sh`, should generate a build successful message. 
I checked the build folder and ava build is successful but with the warning, it gives a false build failure indication.

Currently it generates a warning related to a define `_duk_debugger_attach`
```
# github.com/ava-labs/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:0:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
```

Comments in #14 also mentions the duktape warning and it is the last message in the build process which is a bit ambiguous. Hence their should be a build successful message if the `ava` binary is created.

**Comment by danlaine** [comment]
Good idea. Made a PR: https://github.com/ava-labs/gecko/pull/97

**Comment by danlaine** [comment]
Addressed in https://github.com/ava-labs/gecko/pull/97

Thanks again for the suggestion @aanupam23
