### ISSUE TITLE
Enhancement: Decouple binary generation

### ISSUE THREAD

**Issue by adasari** [ava-labs/gecko#99]
Suggestion: ava and evm binary generation must be separated from gecko/scripts/build.sh

Explanation:
Current gecko/scripts/build.sh is generating ava, evm and xputtest binaries. ava binary is generated from gecko repo and evm binary generated from coreth repo. 
So gecko/scripts/build.sh should not pull coreth repo and generate image of coreth as part of gecko build script.

What is the impact of current scripts:
1. Can coreth and gecko use different go versions and release independently ? No. it is much way complicated.
2. Can move to go modules ? No. gecko mod file doesn't care about dependencies of other repo.

Possible options to look at
1. create build script in coreth repo which generate evm binary and create separate script which invokes all dependent repos to generate binaries and pre or post processes. so that all binaries are available.
2. Move it to monorepo with bazel as build system which simplifies repo management and binary generation based in OS.

Thoughts ?

**Comment by adasari** [comment]
I couldn't remove label bug. please feel free to remove if you guys think it is not fall under bug :)

**Comment by danlaine** [comment]
The build setup isn't perfect, but I think we're going to stick with this build setup for the time being. Closing this issue. My sincere thanks for your suggestion, @adasari
